name: tests

on:
  push:
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [10.*, 11.*, 12.*]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
      - run: composer update --prefer-dist --no-interaction
      - run: ./vendor/bin/pest